Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
""" URL patterns for blogs app. """

from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.posts, name='posts'),
    path('new_post', views.new_post, name='new_post'),
    path('post/<int:post_id>', views.post, name='post'),
    path('edit_post/<int:post_id>', views.edit_post, name='edit_post'),
    path('delete_post/<int:post_id>', views.delete_post, name='delete_post'),
]

users/urls.py
""" URL patterns for users app. """

from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    # Default auth urls.
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
    title = models.CharField(max_length=108)
    text = models.TextField(max_length=2064)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """ Returns title of a blog post in a string. """
        if len(self.title) < 52:
            return self.title
        else:
            return f"{self.title[:52]}..."

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': 'Title', 'text': ''}

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseForbidden

from .models import BlogPost
from .forms import BlogForm


def index(request):
    """ Home page of my blog website. """
    return render(request, 'blogs/index.html')


def posts(request):
    """ Page to show all posts in chronological order. """

    posts = BlogPost.objects.order_by('date_added')
    context = {'posts': posts}
    return render(request, 'blogs/posts.html', context)


def post(request, post_id):
    """ Page to show an individual post. """
    post = BlogPost.objects.get(id=post_id)

    context = {'post': post}
    return render(request, 'blogs/post.html', context)


@login_required
def new_post(request):
    """ Make a new post. """
    if request.method != 'POST':
        form = BlogForm()
    else:
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect('blogs:posts')
    
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)


@login_required
def edit_post(request, post_id):
    """ Edit a existing post. """
    post = BlogPost.objects.get(id=post_id)
    title = post.title

    check_topic_owner(request, post)

    if request.method != 'POST':
        form = BlogForm(instance=post)
    else:
        form = BlogForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:post', post_id=post_id)
    
    context = {'post': post, 'title': title, 'form': form}
    return render(request, 'blogs/edit_post.html', context)


@login_required
def delete_post(request, post_id):
    """ Deletes a post. """
    post = BlogPost.objects.get(id=post_id)

    if check_topic_owner(request, post):
        post.delete()

    context = {'post': post}
    return render(request, 'blogs/delete_post.html', context)

def check_topic_owner(request, post):
    if request.user.is_superuser:
        return True
    
    if request.user != post.owner:
        raise Http404
    else:
        return True

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """ Registration page. """
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('blogs:index')
    
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, inital-scale=1
            shrink-to-fit=no">
            <title>My Blog</title>

            {% bootstrap_css %}
            {% bootstrap_javascript jquery='full' %}
    </head>

    <body>

        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

            <a class="navbar-brand" href="{% url 'blogs:index' %}">
                Learning Log</a>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span></button>
            
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blogs:posts' %}">
                            Blog Posts</a></li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text">Hello, {{ user.username }}</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>

        </nav>

        <main role="main" class="container">
            <div class="pb-2 mb-2 border-bottom">
                {% block page_header %}{% endblock page_header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </main>
    </body>
</html>

blogs/templates/blogs/delete_post.html
{% extends "blogs/base.html" %}

{% block content %}
    <p>{{ post }} has been deleted.</p>
{% endblock content %}

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}

{% block content %}
    <p>Edit post:</p>

    <form action="{% url 'blogs:edit_post' post.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
        <button name="cancel">Cancel</button>
    </form>
{% endblock content%}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block content %}
    <p>A place to post blogs about any number of topics.</p>
{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}

{% block content %}
    <p>Make a new post:</p>

    <form action="{% url 'blogs:new_post' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Create Post</button>
    </form>
{% endblock content %}

blogs/templates/blogs/post.html
{% extends "blogs/base.html" %}

{% block content %}
    {{ post.date_added|date:'M d, Y H:i' }} - {{ post.owner }}
    <h4>{{ post.title|linebreaks }}</h4>
    <p>{{ post.text|linebreaks }}</p>

    <a href="{% url 'blogs:edit_post' post.id %}">Edit post</a> -
    <a href="{% url 'blogs:delete_post' post.id %}">Delete post</a>
{% endblock content %}

blogs/templates/blogs/posts.html
{% extends "blogs/base.html" %}


{% block content %}
    {% for post in posts %}
        <ul>
            <li>
                <p>{{ post.date_added|date:'M d, Y H:i' }} - Author: {{ post.owner }}</p>
                <a href="{% url 'blogs:post' post.id %}">{{ post.title|linebreaks }}</a>
            </li>
        </ul>
    {% empty %}
        <p>No posts have been made yet.</p>
    {% endfor %}

    <a href="{% url 'blogs:new_post' %}">Add post</a>
{% endblock content %}